apiVersion: v1
kind: Secret
metadata:
  name: myssh
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: |
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
    NhAAAAAwEAAQAAAgEA1wYzpSHzI91kDgiYH4XMkcmIoRQ4nwk7cemZIgYxcwhSWekz8b9S
    lEhOTkPbvTV7uvlykAQupAQ96LtVkFv2QBgy1akNG3yMnM8UmURN4ZuBDNLJLLzP1ub7Gr
    iEGCud/gRskqmeTaNmHt8SB7ZriWPGBQTBkdOwsAiVOtqq/vp6F8Dg6WrH4DZlhcB2hb3Y
    cMvGvwcl0qA/C0xy8jnORqAfaqznWUkFOvKEXKonAfYITmcxr2sNQXfFwTLLv3EKio8bMr
    WCS024ZfdEYQirHKwbNYL9lV97yux1cmOqxpE6JgqpJ4VjDO3iVXBK75oOORsz2QyZnArH
    yDoTOeL3+gGb3zKTyzFLE5sIHQYfMTPerCca/J0Jugol4HpwGGUALAZjs5GYxa0i4mC3ud
    YGexHl+2hOOs4HIIYL4pDWsKh9TmAp4C6M5xQkOiVpqLLwo+cqSNMbaCRPo6cihcPc9w3g
    EKdm9vMxkJfPMiu0kzomgroBK1LqmThJwRjm1Gv6eJepIEof9TjcSL7R/9y4FgEQ3EIbj9
    8k98qmE5nL8tNaVUKAX+b2+V5Zm9D3V9qkAm4lzVn2dlka7z9jWy35JZNw42GRr70ApFm1
    jentpEK1dB71Gcnaw/w1k3KWNXq3yYWpaWRO3f8pkJKili1lPeGmfQNdvOxZ+xrGIhJVQE
    cAAAdQm/HIkpvxyJIAAAAHc3NoLXJzYQAAAgEA1wYzpSHzI91kDgiYH4XMkcmIoRQ4nwk7
    cemZIgYxcwhSWekz8b9SlEhOTkPbvTV7uvlykAQupAQ96LtVkFv2QBgy1akNG3yMnM8UmU
    RN4ZuBDNLJLLzP1ub7GriEGCud/gRskqmeTaNmHt8SB7ZriWPGBQTBkdOwsAiVOtqq/vp6
    F8Dg6WrH4DZlhcB2hb3YcMvGvwcl0qA/C0xy8jnORqAfaqznWUkFOvKEXKonAfYITmcxr2
    sNQXfFwTLLv3EKio8bMrWCS024ZfdEYQirHKwbNYL9lV97yux1cmOqxpE6JgqpJ4VjDO3i
    VXBK75oOORsz2QyZnArHyDoTOeL3+gGb3zKTyzFLE5sIHQYfMTPerCca/J0Jugol4HpwGG
    UALAZjs5GYxa0i4mC3udYGexHl+2hOOs4HIIYL4pDWsKh9TmAp4C6M5xQkOiVpqLLwo+cq
    SNMbaCRPo6cihcPc9w3gEKdm9vMxkJfPMiu0kzomgroBK1LqmThJwRjm1Gv6eJepIEof9T
    jcSL7R/9y4FgEQ3EIbj98k98qmE5nL8tNaVUKAX+b2+V5Zm9D3V9qkAm4lzVn2dlka7z9j
    Wy35JZNw42GRr70ApFm1jentpEK1dB71Gcnaw/w1k3KWNXq3yYWpaWRO3f8pkJKili1lPe
    GmfQNdvOxZ+xrGIhJVQEcAAAADAQABAAACACCSOJcrsgWdbvSOlLc3Bf/nbqIydUk8lXFH
    Q1ewvHjXqociw32RJP8qh2y6QWTt3xTkMwMMacw/4D41clvwXOLknNQEoY78/4fD+TN7nJ
    iE0mLmOGxlxXig0H9XB/C+sAC0cYXd2l7vAMnDB0Ynzy5RRhj92XHaMTTZIqchodlciSC5
    VNhxa7Qo8+6eHYCw0JfK0QugF4305tfdTWQnzCP39ApYBUtfEO3BornZWcNQSNMnipKEks
    4h8yYK0xY9bK1ZyXLq+munFZGh3Q0dyl2zga5KGK4xzTILPiyFBcTCZvPa6uNTrzyxeXbG
    ZcjZpeHnSaP35qTedS4oA0A3g1G9E3PHSFdjOfCD3TAm2Jdqv0wkeCDniEN7E0hggnU6xV
    qJJyi3EIBdnqA1aEk9HyTEeSI9S94aDZRooK8Q35g3ERrmvibdPK9rxSNF303mVfyrmrps
    qVSR14iUo4+nrqyj1RE8PKvYKhBuEErseBhWIZwg+YwFbKJsv+qbHyjWgKL0mn7qkVpAFW
    K+6GyLCZEbSp1UIcqRINJQOSlxFU13I1buwEDBZojV6Hp21WMEyd8kij9KyyhQDXGny32B
    FAVQaE2h7tLW7DLdy4uXhxjSea//s/25NnQxY6oC9bR2JrKr5xkxZkqq7ZneWYKv5RuXqO
    RwxGTUxMBubnJwowJBAAABAAlfRhKMyb/pBbTmgHzA5MG8w4pVHlFln94Mnjpdo+dpQBYH
    X/XAKTftpxzvHvQ50IC+FMH2VgPNce1COe9IWUmY7C12AMeAz8ZvMP7gI5Hyag3YuPXRyO
    PPC/Lq76p1SLroeMDVsJYPAkX7j8wlycZZ74oSTzRY/W+/FoIXLq+cS1gzT5AKBmHF4f4W
    Ed5gxPrhtzcbfhFjazpJzV36E+D6DnpxNzr/PeawhBcSY6qmJ++Eam2a6FY8s8uF/HXVnb
    E+rrP8CMcCqtQ8s59lQlVMl32oc8AlqrLAXcsrpFLDNAhepkF1TIdy74+DlgjBpo85z9pq
    0X/pn9c4bVM/YucAAAEBAPcu4mT//lh6QDq7WmHo7nk6QTA6m2cTh9vipeX2V/MDjRurso
    IK/xKsX7MkxplsLAeoIpbG82qBS+2XZgKoPseSdMPm9m6Q2yjC1Md0+mvg0pqggC1F87ZF
    IhiB0hnTTH2ef2W+UnaAmn9aDCKmDd0aD7O2c2aGQbvOe/tzbpWem+q4H0oyVhU40DRoYu
    dLC4XBFuP3EyBr6QGSqNuCMYKf41RL1kuCNWSZuC1ZLMH3KCEFoadBhhp0z4CufiJVVBth
    tRjNmzoTuXhCuzmJM7ycNEB8HHNpJsX4dyU+FBxGAnLy+cw/6IEYM2GIM9L2h6Sh6mX2Xu
    j84l/GzXhZ6/cAAAEBAN6xqb+qj8+Ms7tEqaTc/sDdSChLmkdHJG1jPIuQ5fop3qZ1dXn5
    CBmnt5wuOaJmydUNqGDwHIyi1oQA1FRzxITJuQB6eCEYI0nMqWtvsUc4LLebE+k/lMV5jY
    kFBjzc1uedOP7fMHlOjvohVM+t5o8T2ii3wZgrrqEOclYnmeKPrJw6aD4AB6lUa3NG4hDK
    yHGfa7qNhu7gBz7rqVTia2XI0L1iiaryZUXbdHYvLuiM2AERj+pYKUojoVIGrdtpnVVBle
    RSJhIR/O6W6CI3oRV7BeXDGaNsVZzpHFZtwU5XJNIPnWWQFVEoDbdiqlC94AuzKv4i9H7c
    k2EQDXgYGjEAAAAaZHJldGFuYUBkcmV0YW5hbGVub3ZvLXN1c2UB
